FROM golang:alpine AS builder

RUN apk update && apk add --no-cache git
WORKDIR $GOPATH/src/github.com/bjornm82/data-versioner
COPY . .

RUN ls -alh

RUN go get -d -v

RUN go build -o /go/bin/data-versioner
